name: Build and test

on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [nightly, stable]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run cargo check
        run: cargo check --all --bins --examples --tests
        shell: bash

      - name: Run cargo test
        run: cargo test
        shell: bash

  test_asm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run cargo test asm
        run: cargo test --release --features asm
        shell: bash

  test_nostd:
    name: Test nostd
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - thumbv7em-none-eabi

    steps:
    - uses: actions/checkout@v3

    - uses: dtolnay/rust-toolchain@nightly

    - name: Install xargo
      run: cargo install xargo

    - name: build
      run: xargo build --no-default-features --target ${{ matrix.target }}

  cross_arm:
    name: Arm Cross compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu

    steps:
    - uses: actions/checkout@v3

    - uses: dtolnay/rust-toolchain@nightly

    - name: Install cross
      run: cargo install cross

    - name: check
      run: cross check --target ${{ matrix.target }}

    - name: test
      run: cross test --target ${{ matrix.target }}

    - name: test asm-aarch64
      run: cross test --features asm-aarch64 --target ${{ matrix.target }}

  cross_32bit:
    name: 32bit Cross compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - i686-unknown-linux-gnu
          - powerpc-unknown-linux-gnu
          - powerpc64-unknown-linux-gnu
          - mips-unknown-linux-gnu

    steps:
    - uses: actions/checkout@v3

    - uses: dtolnay/rust-toolchain@nightly

    - name: Install cross
      run: cargo install cross

    - name: check
      run: cross check --target ${{ matrix.target }}

    - name: test
      run: cross test --target ${{ matrix.target }}
